### ISSUE TITLE
Need to run checks (GORULES) on 'goa_uniprot_all_noiea' data 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1102]
These are not in our reports (http://release.geneontology.org/2019-06-09/reports/gorule-report.html)

Looks like the data is going in AmiGO and in all our products without checks ?

**Comment by pgaudet** [comment]
To illustrate: 'GO:0005215 transporter activity' is filtered out by gorule-0000008 for all other files. We do have 50 annotations to GO:0005215 presumably coming from goa_uniprot_all_noiea. 

Pascale

**Comment by kltm** [comment]
branch geneontology/goa_full_process_experiment

**Comment by kltm** [comment]
The latest experiment (https://build.geneontology.org/job/geneontology/job/pipeline/job/issue-go-site-1102-process-goa/) supports the reason that historically this has not been done, but this time with newer tools. Currently, ontobio is on track to time out at 20hrs for this step. I'm re-running the experiment with the timeout limit at 3 days just to get a gross idea of when it would complete.

**Comment by kltm** [comment]
Noting interesting fail after 
`Shell Script -- $MAKECMD -e target/sparta-report.json -- (self time 1d 3h 23min 5s) `
```
20:25:20  Validating source gaf: /var/lib/jenkins/workspace/e_issue-go-site-1102-process-goa/go-site/pipeline/target/groups/goa/goa_uniprot_all-src.gaf
20:27:56  
22:52:19  Zipping /var/lib/jenkins/workspace/e_issue-go-site-1102-process-goa/go-site/pipeline/target/groups/goa/goa_uniprot_all_valid.gaf
23:01:40  Traceback (most recent call last):
23:01:40    File "mypyenv/bin/validate.py", line 618, in <module>
23:01:40      cli()
23:01:40    File "/var/lib/jenkins/workspace/e_issue-go-site-1102-process-goa/go-site/pipeline/mypyenv/lib/python3.5/site-packages/click/core.py", line 722, in __call__
23:01:40      return self.main(*args, **kwargs)
23:01:40    File "/var/lib/jenkins/workspace/e_issue-go-site-1102-process-goa/go-site/pipeline/mypyenv/lib/python3.5/site-packages/click/core.py", line 697, in main
23:01:40      rv = self.invoke(ctx)
23:01:40    File "/var/lib/jenkins/workspace/e_issue-go-site-1102-process-goa/go-site/pipeline/mypyenv/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
23:01:40      return _process_result(sub_ctx.command.invoke(sub_ctx))
23:01:40    File "/var/lib/jenkins/workspace/e_issue-go-site-1102-process-goa/go-site/pipeline/mypyenv/lib/python3.5/site-packages/click/core.py", line 895, in invoke
23:01:40      return ctx.invoke(self.callback, **ctx.params)
23:01:40    File "/var/lib/jenkins/workspace/e_issue-go-site-1102-process-goa/go-site/pipeline/mypyenv/lib/python3.5/site-packages/click/core.py", line 535, in invoke
23:01:40      return callback(*args, **kwargs)
23:01:40    File "mypyenv/bin/validate.py", line 584, in produce
23:01:40      suppress_rule_reporting_tags=suppress_rule_reporting_tag)[0]
23:01:40    File "mypyenv/bin/validate.py", line 39, in wrapper
23:01:40      zipup(o)
23:01:40    File "mypyenv/bin/validate.py", line 55, in zipup
23:01:40      tf.write(p.read())
23:01:40    File "/usr/lib/python3.5/gzip.py", line 262, in write
23:01:40      self.fileobj.write(self.compress.compress(data))
23:01:40  OverflowError: Size does not fit in an unsigned int
23:01:40  Makefile:63: recipe for target 'target/groups/goa/goa.group' failed
23:01:40  make: *** [target/groups/goa/goa.group] Error 1
```
@dougli1sqrd I think to be fair here, we should probably be treating goa_uniprot_all_noiea as a product we produce first and then work from there, rather than attacking goa_uniprot_all directly.

**Comment by pgaudet** [comment]
@kltm I dont think we intend to do this? 

Close?

**Comment by pgaudet** [comment]
not relevant for the new GOC-GOA data exchange pipeline.
